// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';


var isPROD = +(process.env.NODE_ENV === "production");

function dangerousHtml(html) {
  return {
          __html: html
        };
}

export {
  isPROD        ,
  dangerousHtml ,
  
}
/* isPROD Not a pure module */
