// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

import * as ReactDom                 from "react-dom";
import * as ReasonReact              from "reason-react/src/ReasonReact.js";
import * as ReactHotLoader           from "react-hot-loader";
import * as RegisterServiceWorker    from "./registerServiceWorker";
import * as Root$ReasonReactStarter  from "./root.bs.js";
import * as Utils$ReasonReactStarter from "./utils/utils.bs.js";

function make(children) {
  return ReasonReact.wrapJsForReason(ReactHotLoader.AppContainer, { }, children);
}

var AppContainer = /* module */[/* make */make];

var rootId = document.getElementById("root");

var app = Utils$ReasonReactStarter.isPROD !== 0 ? ReasonReact.element(/* None */0, /* None */0, Root$ReasonReactStarter.make(/* array */[])) : ReasonReact.element(/* None */0, /* None */0, make(/* array */[ReasonReact.element(/* None */0, /* None */0, Root$ReasonReactStarter.make(/* array */[]))]));

ReactDom.hydrate(app, rootId);

if (module.hot) {
  module.hot.accept();
}

RegisterServiceWorker.default();

export {
  AppContainer ,
  rootId       ,
  app          ,
  
}
/* rootId Not a pure module */
