// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

import * as React       from "react";
import * as ReasonReact from "reason-react/src/ReasonReact.js";

var component = ReasonReact.statelessComponent("Root");

function make() {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("div", {
                  className: "App"
                }, React.createElement("div", {
                      className: "App-header"
                    }, React.createElement("h2", undefined, "Welcome to React and Reason")), React.createElement("p", {
                      className: "App-intro"
                    }, "To get started, edit", React.createElement("code", undefined, " src/App.re "), "and save to reload."));
    });
  return newrecord;
}

export {
  component ,
  make      ,
  
}
/* component Not a pure module */
